### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by VanessaAzocar** [VanessaAzocar/scl-2018-05-bc-core-am-datadashboard#13]
cami, has podido arreglar con bootstrap el menú?, yo estoy probando

**Comment by CamiRamirez** [comment]
Vane, te envío el menú con bootstrap funcionando, arregle algunas cosas (tamaño login, y algunos detalles del responsive) y cambie la parte de busqueda de nombres pero hay que cambiarle estilo y demases, porque tiene colores que no van :)

**Comment by VanessaAzocar** [comment]
super, haz un pull porfa para verlo y modificar lo que me comentas.
