### ISSUE TITLE
listado de postulantes en html

### ISSUE THREAD

**Issue by CamiRamirez** [VanessaAzocar/scl-2018-05-bc-core-am-datadashboard#18]
Vane, agregue el listado de nombres al html, podemos mejorar los estilos obviamente jeje tambien le di color al menú y centre los nombres de las ciudades. Ahí notaras algunos cambios cuando lo veas, cuéntame cualquier cosa :)

**Comment by VanessaAzocar** [comment]
Si los vi cami, quedo buenísimo, vamos super bien!!! :)
